# Generated by Django 3.1.2 on 2021-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepriselemka',
            name='a_propos_complet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrepriselemka',
            name='a_propos_resume',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
