# Generated by Django 3.1.8 on 2021-05-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ref_catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemka.catalogue'),
        ),
    ]
