# Generated by Django 3.1.2 on 2021-02-01 18:55

from django.db import migrations, models
import django.db.models.deletion
import lemka.utils


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'ordering': ['ref_ville__ref_pays__pays', 'ref_ville__ville']},
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='ref_user',
        ),
        migrations.AddField(
            model_name='user',
            name='ref_adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresse', to='lemka.adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=lemka.utils.path_and_rename_user_image),
        ),
    ]
