# Generated by Django 3.1.2 on 2021-04-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
