# Generated by Django 3.1.2 on 2021-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
