# Generated by Django 3.1.2 on 2021-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedevis',
            name='en_cours',
            field=models.BooleanField(default=False),
        ),
    ]
