# Generated by Django 3.1.2 on 2021-04-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandedevis',
            name='en_cours',
        ),
    ]
