# Generated by Django 3.1.8 on 2021-06-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ref_rayon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lemka.rayon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ref_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lemka.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ref_type_produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lemka.typeproduit'),
            preserve_default=False,
        ),
    ]
