# Generated by Django 3.1.8 on 2021-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensuration',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='mensuration',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
