# Generated by Django 3.1.2 on 2021-04-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandedevis',
            options={'ordering': ['-created_at']},
        ),
    ]
