# Generated by Django 3.1.2 on 2021-04-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0002_auto_20210426_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemadeDevisImage',
        ),
    ]
