# Generated by Django 3.1.2 on 2021-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0002_delete_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ref_tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='lemka.Tag'),
        ),
    ]
