# Generated by Django 3.1.2 on 2021-04-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0002_demandedevis_en_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercerieoption',
            name='ref_tva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tva', to='lemka.tva'),
            preserve_default=False,
        ),
    ]
