# Generated by Django 3.1.2 on 2021-05-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0002_auto_20210512_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermesure',
            options={},
        ),
        migrations.RenameField(
            model_name='rayon',
            old_name='rayon',
            new_name='nom',
        ),
    ]
