# Generated by Django 3.1.8 on 2021-06-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0002_auto_20210609_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ville',
            options={'ordering': ['code_postale']},
        ),
    ]
