# Generated by Django 3.1.2 on 2021-05-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0003_delete_demadedevisimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['date', 'start']},
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='ref_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemka.devis'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='ref_type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemka.typeservice'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='ref_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
