# Generated by Django 3.1.8 on 2021-06-09 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0003_auto_20210609_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='jour',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='jour_semaine',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
