# Generated by Django 3.1.8 on 2021-05-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0003_auto_20210529_0103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrepriseLemka',
            new_name='Entreprise',
        ),
    ]
