# Generated by Django 3.1.2 on 2021-04-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0003_mercerieoption_ref_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedevis',
            name='ref_mensuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemka.usermensuration'),
        ),
    ]
