# Generated by Django 3.1.2 on 2021-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0004_auto_20210219_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercerie',
            name='description',
        ),
        migrations.AddField(
            model_name='mercerieoption',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
