# Generated by Django 3.1.2 on 2021-05-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0004_auto_20210525_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduit',
            options={},
        ),
        migrations.RenameField(
            model_name='typeproduit',
            old_name='type_produit',
            new_name='nom',
        ),
    ]
