# Generated by Django 3.1.2 on 2021-04-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0004_auto_20210415_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='ref_devis',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='ref_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='lemka.devis'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='ref_type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemka.typeservice', verbose_name='service'),
        ),
    ]
