# Generated by Django 3.1.2 on 2021-05-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0004_auto_20210502_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date', '-start']},
        ),
    ]
