# Generated by Django 3.1.2 on 2021-03-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0005_auto_20210305_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercerie',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mercerieoption',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
    ]
