# Generated by Django 3.1.8 on 2021-06-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0005_auto_20210610_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ref_catalogue',
        ),
    ]
