# Generated by Django 3.1.2 on 2021-05-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0005_auto_20210525_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeservice',
            old_name='type_service',
            new_name='nom',
        ),
    ]
