# Generated by Django 3.1.2 on 2021-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0005_auto_20210505_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepriselemka',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepriselemka',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepriselemka',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepriselemka',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
