# Generated by Django 3.1.2 on 2021-04-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0005_auto_20210415_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ref_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='lemka.Tag'),
        ),
    ]
