# Generated by Django 3.1.2 on 2021-03-05 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0006_auto_20210305_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='mercerieoption',
            name='taille',
        ),
        migrations.CreateModel(
            name='MercerieOptionDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999.9)])),
                ('ref_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemka.dimension')),
                ('ref_mercerie_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemka.mercerieoption')),
            ],
        ),
    ]
