# Generated by Django 3.1.2 on 2021-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0006_auto_20210507_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermensuration',
            name='remarque',
            field=models.TextField(blank=True),
        ),
    ]
