# Generated by Django 3.1.2 on 2021-04-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0006_auto_20210416_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='ref_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='lemka.article'),
        ),
        migrations.AlterField(
            model_name='demandedevis',
            name='ref_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemka.article'),
        ),
    ]
