# Generated by Django 3.1.2 on 2021-05-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0006_auto_20210525_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='nom',
        ),
    ]
