# Generated by Django 3.1.2 on 2021-03-05 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0007_auto_20210305_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercerieoption',
            name='prix_u_ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999.99)]),
        ),
    ]
