# Generated by Django 3.1.2 on 2021-04-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0007_auto_20210418_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemka.genre', verbose_name='Sexe'),
        ),
    ]
