# Generated by Django 3.1.8 on 2021-06-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0007_delete_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ref_type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lemka.typeservice'),
        ),
    ]
