# Generated by Django 3.1.2 on 2021-05-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0007_usermensuration_remarque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMensurationMesure',
            new_name='UserMesure',
        ),
    ]
