# Generated by Django 3.1.8 on 2021-06-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0008_auto_20210610_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeService',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='ref_type_service',
            new_name='ref_service',
        ),
        migrations.RenameField(
            model_name='demandedevis',
            old_name='ref_type_service',
            new_name='ref_service',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='ref_type_service',
            new_name='ref_service',
        ),
    ]
