# Generated by Django 3.1.2 on 2021-05-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0009_auto_20210525_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tva',
            options={},
        ),
    ]
