# Generated by Django 3.1.2 on 2021-03-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0009_auto_20210305_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercerieoptiondimension',
            options={'ordering': ['ref_mercerie_option__ref_mercerie__nom']},
        ),
    ]
