# Generated by Django 3.1.2 on 2021-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0010_auto_20210305_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercerieoption',
            name='reference',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
