# Generated by Django 3.1.2 on 2021-03-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0011_auto_20210309_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dimension',
            new_name='Caracteristique',
        ),
        migrations.RenameModel(
            old_name='MercerieOptionDimension',
            new_name='MercerieOptionCaracteristique',
        ),
        migrations.RenameField(
            model_name='mercerieoptioncaracteristique',
            old_name='ref_dimension',
            new_name='ref_caracteristique',
        ),
        migrations.AlterField(
            model_name='mercerieoptionimage',
            name='ref_mercerie_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lemka.mercerieoption'),
        ),
    ]
