# Generated by Django 3.1.2 on 2021-03-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0012_auto_20210311_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandedevis',
            name='ref_catalogue',
        ),
    ]
