# Generated by Django 3.1.2 on 2021-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0013_remove_demandedevis_ref_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedevis',
            name='numero_demande_devis',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
