# Generated by Django 3.1.2 on 2021-03-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0014_auto_20210317_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensurationusermensuration',
            options={'ordering': ['ref_user_mensuration__ref_user__username', '-ref_user_mensuration__is_main', 'ref_mensuration__id']},
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='ref_article',
            field=models.ForeignKey(on_delete=models.Model, related_name='imgs', to='lemka.article'),
        ),
        migrations.RemoveField(
            model_name='demandedevis',
            name='ref_article',
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='ref_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lemka.article'),
        ),
    ]
