# Generated by Django 3.1.2 on 2021-03-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0015_auto_20210322_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandedevis',
            name='ref_mensuration',
        ),
        migrations.AddField(
            model_name='demandedevis',
            name='ref_mensuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lemka.usermensuration'),
        ),
    ]
