# Generated by Django 3.1.2 on 2021-03-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0016_auto_20210323_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercerieoptioncaracteristique',
            name='ref_mercerie_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catacteristiques', to='lemka.mercerieoption'),
        ),
    ]
