# Generated by Django 3.1.2 on 2021-03-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0017_auto_20210324_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='ref_bon_commande',
        ),
        migrations.DeleteModel(
            name='BonCommande',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
