# Generated by Django 3.1.2 on 2021-03-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0018_auto_20210326_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensurationUserMensuration',
            new_name='UserMensurationMesure',
        ),
    ]
