# Generated by Django 3.1.2 on 2021-03-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0019_auto_20210326_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='ref_accompte',
        ),
        migrations.DeleteModel(
            name='AccompteDemande',
        ),
    ]
