# Generated by Django 3.1.2 on 2021-04-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0020_auto_20210326_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mercerieoption',
            name='ref_mercerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lemka.mercerie'),
        ),
    ]
