# Generated by Django 3.1.2 on 2021-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0021_auto_20210402_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='remarque',
            field=models.TextField(default=''),
        ),
    ]
