# Generated by Django 3.1.2 on 2021-04-03 11:26

from django.db import migrations, models
import lemka.utils


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0022_auto_20210402_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demadedevisimage',
            name='image',
            field=models.ImageField(upload_to=lemka.utils.path_and_rename_demande_devis_image),
        ),
    ]
