# Generated by Django 3.1.2 on 2021-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0023_auto_20210403_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='est_accepte',
            field=models.BooleanField(null=True),
        ),
    ]
