# Generated by Django 3.1.2 on 2021-04-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemka', '0024_auto_20210404_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='ref_demande_devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemka.demandedevis'),
        ),
    ]
